name = "Blueberry Flavored Aeronautics"
author = "FeeelinBlu"
version = "0.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc0d5baad7a68b8e79a88f0db39395078eb2e7091a32fb5f7dbabac079585cff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
