name = "Blueberry Flavored Aeronautics"
author = "FeeelinBlu"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11a9839f9cf3892084f9a99a9f7ed6e49c215d9c8f613773a1579861e7ca7ddb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
