name = "Blueberry Flavored Aeronautics"
author = "FeeelinBlu"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd3a37747f6dfdfe120feb49f1b2e4eb630a3c9a2e217a2a6ddc9d74a09aa9a6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
